"""
GEMINI AI Integration Service for ISO 19011 Compliant Report Generation

This service integrates with Google GEMINI AI to generate automated audit reports
that strictly follow ISO 19011:2018 Clause 6.5 requirements.
"""

import os
import json
import logging
from typing import Dict, Any, Optional, List
from datetime import datetime
import google.generativeai as genai
from sqlalchemy.orm import Session
from app.models import Audit, AuditFinding, AuditEvidence, AuditChecklist, User, Department, CAPAItem, AuditTeam
from app.database import get_db

logger = logging.getLogger(__name__)

class GeminiAIService:
    """
    GEMINI AI service for automated ISO 19011 compliant report generation.
    
    Implements ISO 19011:2018 Clause 6.5 requirements:
    - Audit objectives, scope and criteria (6.5.2(a))
    - Identification of audit team and auditee representatives (6.5.2(b))
    - Dates and locations where audit activities were conducted (6.5.2(c))
    - Identification of documents used as audit criteria (6.5.2(d))
    - Audit findings and evidence (6.5.2(e))
    - Audit conclusions (6.5.2(f))
    """
    
    def __init__(self):
        """Initialize GEMINI AI service with authentication and configuration."""
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.model_name = os.getenv("GEMINI_MODEL", "gemini-1.5-pro")
        
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")
        
        # Configure GEMINI AI
        genai.configure(api_key=self.api_key)
        self.model = genai.GenerativeModel(self.model_name)
        
        # ISO 19011 compliant report template
        self.iso_19011_template = self._load_iso_19011_template()
    
    def _load_iso_19011_template(self) -> str:
        """
        Load ISO 19011:2018 Clause 6.5.2 compliant report template.
        
        Returns:
            str: ISO 19011 compliant report structure template
        """
        return """
# AUDIT REPORT

## 1. EXECUTIVE SUMMARY
[Provide a concise summary of audit conclusions per ISO 19011 Clause 6.5.2(f)]

## 2. AUDIT IDENTIFICATION (ISO 19011 Clause 6.5.2(a))
- **Audit Objectives:** {audit_objectives}
- **Audit Scope:** {audit_scope}
- **Audit Criteria:** {audit_criteria}

## 3. AUDIT TEAM AND PARTICIPANTS (ISO 19011 Clause 6.5.2(b))
- **Lead Auditor:** {lead_auditor}
- **Audit Team Members:** {audit_team}
- **Auditee Organization:** {auditee_organization}
- **Auditee Representatives:** {auditee_representatives}

## 4. AUDIT DATES AND LOCATIONS (ISO 19011 Clause 6.5.2(c))
- **Audit Start Date:** {start_date}
- **Audit End Date:** {end_date}
- **Audit Locations:** {audit_locations}

## 5. AUDIT CRITERIA DOCUMENTS (ISO 19011 Clause 6.5.2(d))
{audit_criteria_documents}

## 6. DETAILED AUDIT FINDINGS (ISO 19011 Clause 6.5.2(e))

### 6.1 Conformities
{conformities}

### 6.2 Non-Conformities
{non_conformities}

### 6.3 Opportunities for Improvement
{opportunities_for_improvement}

## 7. AUDIT CONCLUSIONS (ISO 19011 Clause 6.5.2(f))
### 7.1 Degree of Conformity with Audit Criteria
{degree_of_conformity}

### 7.2 Overall Assessment
{overall_assessment}

## 8. CORRECTIVE AND PREVENTIVE ACTION RECOMMENDATIONS
{capa_recommendations}

## 9. DISTRIBUTION LIST (ISO 19011 Clause 6.5.3)
{distribution_list}

---
**Report Generated:** {generation_date}
**Generated By:** GEMINI AI Report Generation System
**ISO 19011:2018 Compliant:** Yes
"""

    async def generate_audit_report(self, audit_id: str, db: Session) -> Dict[str, Any]:
        """
        Generate ISO 19011 compliant audit report using GEMINI AI.
        
        Args:
            audit_id (str): UUID of the audit to generate report for
            db (Session): Database session
            
        Returns:
            Dict[str, Any]: Generated report data with content and metadata
            
        Raises:
            ValueError: If audit not found or data incomplete
            Exception: If GEMINI AI generation fails
        """
        try:
            # Aggregate audit data per ISO 19011 requirements
            audit_data = await self._aggregate_audit_data(audit_id, db)
            
            # Validate data completeness for ISO compliance
            self._validate_iso_compliance(audit_data)
            
            # Generate report content using GEMINI AI
            report_content = await self._generate_report_content(audit_data)
            
            # Validate generated report for ISO 19011 compliance
            validation_result = await self._validate_report_compliance(report_content, audit_data)
            
            return {
                "content": report_content,
                "audit_id": audit_id,
                "generation_date": datetime.utcnow().isoformat(),
                "iso_compliance_validated": validation_result["is_compliant"],
                "validation_notes": validation_result["notes"],
                "word_count": len(report_content.split()),
                "sections_generated": self._count_report_sections(report_content)
            }
            
        except Exception as e:
            logger.error(f"Failed to generate audit report for audit {audit_id}: {str(e)}")
            raise Exception(f"Report generation failed: {str(e)}")

    async def _aggregate_audit_data(self, audit_id: str, db: Session) -> Dict[str, Any]:
        """
        Aggregate all audit data required for ISO 19011 compliant report.
        
        Implements systematic collection per ISO 19011 Clause 6.4.5 (objective evidence)
        and Clause 6.4.7 (audit findings correlation).
        
        Args:
            audit_id (str): Audit UUID
            db (Session): Database session
            
        Returns:
            Dict[str, Any]: Comprehensive audit data structure
        """
        # Get audit basic information
        audit = db.query(Audit).filter(Audit.id == audit_id).first()
        if not audit:
            raise ValueError(f"Audit with ID {audit_id} not found")
        
        # Get audit team information (ISO 19011 Clause 6.5.2(b))
        lead_auditor = db.query(User).filter(User.id == audit.lead_auditor_id).first() if audit.lead_auditor_id else None
        audit_team = db.query(User).join(AuditTeam).filter(AuditTeam.audit_id == audit_id).all()
        auditee_contact = db.query(User).filter(User.id == audit.auditee_contact_person_id).first() if audit.auditee_contact_person_id else None
        
        # Get audit findings (ISO 19011 Clause 6.5.2(e))
        findings = db.query(AuditFinding).filter(AuditFinding.audit_id == audit_id).all()
        
        # Get audit evidence (ISO 19011 Clause 3.3 - objective evidence)
        evidence = db.query(AuditEvidence).filter(AuditEvidence.audit_id == audit_id).all()
        
        # Get checklist items and compliance scores
        checklists = db.query(AuditChecklist).filter(AuditChecklist.audit_id == audit_id).all()
        
        # Get CAPA items for recommendations
        capa_items = db.query(CAPAItem).filter(CAPAItem.audit_id == audit_id).all()
        
        # Get department information
        department = db.query(Department).filter(Department.id == audit.department_id).first() if audit.department_id else None
        
        return {
            # ISO 19011 Clause 6.5.2(a) - Audit identification
            "audit": {
                "id": str(audit.id),
                "title": audit.title,
                "objectives": audit.audit_objectives or "Not specified",
                "scope": audit.audit_scope_detailed or audit.scope or "Not specified",
                "criteria": audit.audit_criteria or "Not specified",
                "methodology": audit.audit_methodology or "Standard audit methodology",
                "status": audit.status.value,
                "year": audit.year
            },
            
            # ISO 19011 Clause 6.5.2(b) - Audit team and participants
            "team": {
                "lead_auditor": {
                    "name": lead_auditor.full_name if lead_auditor else "Not assigned",
                    "email": lead_auditor.email if lead_auditor else None,
                    "role": lead_auditor.role.value if lead_auditor else None
                },
                "team_members": [
                    {
                        "name": member.full_name,
                        "email": member.email,
                        "role": member.role.value
                    } for member in audit_team
                ],
                "auditee_organization": audit.auditee_organization or "Not specified",
                "auditee_contact": {
                    "name": auditee_contact.full_name if auditee_contact else "Not specified",
                    "email": auditee_contact.email if auditee_contact else None
                }
            },
            
            # ISO 19011 Clause 6.5.2(c) - Dates and locations
            "schedule": {
                "start_date": audit.start_date.isoformat() if audit.start_date else "Not scheduled",
                "end_date": audit.end_date.isoformat() if audit.end_date else "Not scheduled",
                "location": audit.auditee_location or "Not specified"
            },
            
            # ISO 19011 Clause 6.5.2(d) - Audit criteria documents
            "criteria_documents": self._extract_criteria_documents(evidence),
            
            # ISO 19011 Clause 6.5.2(e) - Audit findings and evidence
            "findings": [
                {
                    "id": str(finding.id),
                    "title": finding.title,
                    "severity": finding.severity.value,
                    "impact": finding.impact or "Not specified",
                    "root_cause": finding.root_cause or "Under investigation",
                    "recommendation": finding.recommendation or "To be determined",
                    "status": finding.status,
                    "auditee_response": finding.response_from_auditee or "Pending response"
                } for finding in findings
            ],
            
            # Objective evidence per ISO 19011 Clause 3.3
            "evidence": [
                {
                    "id": str(ev.id),
                    "file_name": ev.file_name,
                    "description": ev.description or "No description",
                    "type": ev.evidence_type or "document",
                    "category": ev.evidence_category or "general",
                    "is_objective": ev.is_objective_evidence,
                    "collection_method": ev.collection_method or "document_review",
                    "timestamp": ev.evidence_timestamp.isoformat() if ev.evidence_timestamp else ev.created_at.isoformat()
                } for ev in evidence
            ],
            
            # Compliance assessment data
            "compliance": {
                "checklists": [
                    {
                        "clause_reference": checklist.clause_reference,
                        "clause_title": checklist.clause_title,
                        "compliance_status": checklist.compliance_status.value,
                        "compliance_score": checklist.compliance_score,
                        "notes": checklist.notes or "No notes"
                    } for checklist in checklists
                ],
                "overall_score": self._calculate_overall_compliance_score(checklists)
            },
            
            # CAPA recommendations
            "capa_items": [
                {
                    "id": str(capa.id),
                    "capa_number": capa.capa_number,
                    "type": capa.capa_type.value,
                    "title": capa.title,
                    "description": capa.description or "No description",
                    "corrective_action": capa.corrective_action or "To be defined",
                    "preventive_action": capa.preventive_action or "To be defined",
                    "due_date": capa.due_date.isoformat() if capa.due_date else "Not set",
                    "status": capa.status.value,
                    "priority": capa.priority
                } for capa in capa_items
            ],
            
            # Department and organizational context
            "organization": {
                "department": department.name if department else "Not specified",
                "created_by": audit.created_by.full_name if audit.created_by else "System"
            }
        }

    def _extract_criteria_documents(self, evidence: List[AuditEvidence]) -> List[Dict[str, str]]:
        """Extract audit criteria documents from evidence."""
        criteria_docs = []
        for ev in evidence:
            if ev.evidence_category in ["policy", "procedure", "standard", "regulation"]:
                criteria_docs.append({
                    "name": ev.file_name,
                    "description": ev.description or "Audit criteria document",
                    "type": ev.evidence_category
                })
        return criteria_docs

    def _calculate_overall_compliance_score(self, checklists: List[AuditChecklist]) -> int:
        """Calculate overall compliance score from checklist items."""
        if not checklists:
            return 0
        
        total_score = sum(checklist.compliance_score for checklist in checklists)
        return round(total_score / len(checklists))

    async def _generate_report_content(self, audit_data: Dict[str, Any]) -> str:
        """
        Generate report content using GEMINI AI with ISO 19011 compliance.
        
        Args:
            audit_data (Dict[str, Any]): Aggregated audit data
            
        Returns:
            str: Generated report content in markdown format
        """
        # Prepare GEMINI prompt with ISO 19011 requirements
        prompt = self._create_iso_19011_prompt(audit_data)
        
        try:
            # Generate content using GEMINI AI
            response = self.model.generate_content(prompt)
            
            if not response.text:
                raise Exception("GEMINI AI returned empty response")
            
            return response.text
            
        except Exception as e:
            logger.error(f"GEMINI AI generation failed: {str(e)}")
            raise Exception(f"AI report generation failed: {str(e)}")

    def _create_iso_19011_prompt(self, audit_data: Dict[str, Any]) -> str:
        """
        Create ISO 19011 compliant prompt for GEMINI AI.
        
        Args:
            audit_data (Dict[str, Any]): Audit data structure
            
        Returns:
            str: Formatted prompt for GEMINI AI
        """
        return f"""
You are an expert audit report writer specializing in ISO 19011:2018 compliant audit reports.

Generate a comprehensive audit report that strictly follows ISO 19011:2018 Clause 6.5 requirements.

MANDATORY REQUIREMENTS (ISO 19011 Clause 6.5.2):
1. Use objective, factual language throughout
2. Include all required sections per ISO 19011 Clause 6.5.2
3. Ensure audit conclusions are supported by objective evidence
4. Use standardized ISO audit terminology
5. Maintain professional, impartial tone

AUDIT DATA:
{json.dumps(audit_data, indent=2, default=str)}

REPORT STRUCTURE REQUIREMENTS:
1. Executive Summary with clear audit conclusions
2. Audit identification (objectives, scope, criteria)
3. Audit team and auditee identification
4. Audit dates and locations
5. Audit criteria documents used
6. Detailed findings with objective evidence
7. Audit conclusions with degree of conformity assessment
8. CAPA recommendations based on findings

COMPLIANCE REQUIREMENTS:
- Use ISO 19011 terminology (conformity/non-conformity, objective evidence, audit findings)
- Classify findings as: Conformities, Non-conformities, Opportunities for Improvement
- Provide evidence-based conclusions only
- Include degree of conformity assessment per ISO 19011 Clause 6.5.2(f)
- Maintain objectivity and avoid subjective opinions

Generate the complete audit report in markdown format following the structure above.
"""

    def _validate_iso_compliance(self, audit_data: Dict[str, Any]) -> None:
        """
        Validate audit data completeness for ISO 19011 compliance.
        
        Args:
            audit_data (Dict[str, Any]): Audit data to validate
            
        Raises:
            ValueError: If required ISO 19011 data is missing
        """
        required_fields = [
            ("audit.objectives", "Audit objectives are required per ISO 19011 Clause 6.5.2(a)"),
            ("audit.scope", "Audit scope is required per ISO 19011 Clause 6.5.2(a)"),
            ("audit.criteria", "Audit criteria are required per ISO 19011 Clause 6.5.2(a)"),
            ("team.lead_auditor.name", "Lead auditor identification required per ISO 19011 Clause 6.5.2(b)"),
            ("schedule.start_date", "Audit dates are required per ISO 19011 Clause 6.5.2(c)")
        ]
        
        for field_path, error_message in required_fields:
            if not self._get_nested_value(audit_data, field_path):
                raise ValueError(error_message)

    def _get_nested_value(self, data: Dict[str, Any], path: str) -> Any:
        """Get nested dictionary value using dot notation."""
        keys = path.split('.')
        value = data
        for key in keys:
            if isinstance(value, dict) and key in value:
                value = value[key]
            else:
                return None
        return value

    async def _validate_report_compliance(self, report_content: str, audit_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate generated report for ISO 19011 compliance.
        
        Args:
            report_content (str): Generated report content
            audit_data (Dict[str, Any]): Original audit data
            
        Returns:
            Dict[str, Any]: Validation results with compliance status and notes
        """
        validation_notes = []
        is_compliant = True
        
        # Check for required ISO 19011 sections
        required_sections = [
            "EXECUTIVE SUMMARY",
            "AUDIT IDENTIFICATION",
            "AUDIT TEAM AND PARTICIPANTS", 
            "AUDIT DATES AND LOCATIONS",
            "AUDIT CRITERIA DOCUMENTS",
            "DETAILED AUDIT FINDINGS",
            "AUDIT CONCLUSIONS"
        ]
        
        for section in required_sections:
            if section not in report_content.upper():
                validation_notes.append(f"Missing required section: {section}")
                is_compliant = False
        
        # Check for ISO terminology usage
        iso_terms = ["conformity", "non-conformity", "objective evidence", "audit findings"]
        for term in iso_terms:
            if term.lower() not in report_content.lower():
                validation_notes.append(f"Consider including ISO term: {term}")
        
        # Check content length (should be comprehensive)
        if len(report_content.split()) < 500:
            validation_notes.append("Report may be too brief for comprehensive audit coverage")
            is_compliant = False
        
        return {
            "is_compliant": is_compliant,
            "notes": validation_notes,
            "sections_found": len([s for s in required_sections if s in report_content.upper()]),
            "total_sections_required": len(required_sections)
        }

    def _count_report_sections(self, report_content: str) -> int:
        """Count the number of sections in the generated report."""
        return len([line for line in report_content.split('\n') if line.startswith('#')])